/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CausesDisplaySchema,
  ExtensionConfig,
  GetUserRelatedSchedule200Response,
  GetUserRelations200Response,
  JJCampaign,
  JJCampaigns,
  OverviewSchema,
  UserExtensionConfig,
  UserScheduleSchema,
  YogsScheduleSchema,
} from '../models/index';
import {
    CausesDisplaySchemaFromJSON,
    CausesDisplaySchemaToJSON,
    ExtensionConfigFromJSON,
    ExtensionConfigToJSON,
    GetUserRelatedSchedule200ResponseFromJSON,
    GetUserRelatedSchedule200ResponseToJSON,
    GetUserRelations200ResponseFromJSON,
    GetUserRelations200ResponseToJSON,
    JJCampaignFromJSON,
    JJCampaignToJSON,
    JJCampaignsFromJSON,
    JJCampaignsToJSON,
    OverviewSchemaFromJSON,
    OverviewSchemaToJSON,
    UserExtensionConfigFromJSON,
    UserExtensionConfigToJSON,
    UserScheduleSchemaFromJSON,
    UserScheduleSchemaToJSON,
    YogsScheduleSchemaFromJSON,
    YogsScheduleSchemaToJSON,
} from '../models/index';

export interface GetCampaignsRequest {
    channelId: string;
    userId: string;
}

export interface GetCausesRequest {
    channelId: string;
    userId: string;
}

export interface GetExtensionConfigRequest {
    channelId: string;
    userId: string;
}

export interface GetOverviewRequest {
    channelId: string;
    userId: string;
}

export interface GetUserDataRequest {
    channelId: string;
    userId: string;
}

export interface GetUserExtensionConfigRequest {
    channelId: string;
    userId: string;
}

export interface GetUserRelatedScheduleRequest {
    channelId: string;
    userId: string;
}

export interface GetUserRelationsRequest {
    channelId: string;
    userId: string;
}

export interface GetUserScheduleRequest {
    channelId: string;
    userId: string;
}

export interface GetYogsScheduleRequest {
    channelId: string;
    userId: string;
}

/**
 * 
 */
export class TwitchExtensionApi extends runtime.BaseAPI {

    /**
     * Retrieve all campaigns from the jj api
     * Get campaigns
     */
    async getCampaignsRaw(requestParameters: GetCampaignsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JJCampaigns>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getCampaigns().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getCampaigns().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/campaigns/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JJCampaignsFromJSON(jsonValue));
    }

    /**
     * Retrieve all campaigns from the jj api
     * Get campaigns
     */
    async getCampaigns(requestParameters: GetCampaignsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JJCampaigns> {
        const response = await this.getCampaignsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all causes from the jj api
     * Get causes
     */
    async getCausesRaw(requestParameters: GetCausesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CausesDisplaySchema>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getCauses().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getCauses().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/causes/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CausesDisplaySchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve all causes from the jj api
     * Get causes
     */
    async getCauses(requestParameters: GetCausesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CausesDisplaySchema> {
        const response = await this.getCausesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the extension configuration
     * Get the extension configuration
     */
    async getExtensionConfigRaw(requestParameters: GetExtensionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExtensionConfig>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getExtensionConfig().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getExtensionConfig().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/config/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExtensionConfigFromJSON(jsonValue));
    }

    /**
     * Get the extension configuration
     * Get the extension configuration
     */
    async getExtensionConfig(requestParameters: GetExtensionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExtensionConfig> {
        const response = await this.getExtensionConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve overview from the jj api
     * Get overview
     */
    async getOverviewRaw(requestParameters: GetOverviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverviewSchema>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getOverview().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getOverview().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/overview/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OverviewSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve overview from the jj api
     * Get overview
     */
    async getOverview(requestParameters: GetOverviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverviewSchema> {
        const response = await this.getOverviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the use data
     * Get the users data
     */
    async getUserDataRaw(requestParameters: GetUserDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JJCampaign>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getUserData().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserData().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/user-data/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JJCampaignFromJSON(jsonValue));
    }

    /**
     * Get the use data
     * Get the users data
     */
    async getUserData(requestParameters: GetUserDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JJCampaign> {
        const response = await this.getUserDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the user extension configuration
     * Get the user extension configuration
     */
    async getUserExtensionConfigRaw(requestParameters: GetUserExtensionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserExtensionConfig>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getUserExtensionConfig().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserExtensionConfig().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/user-config/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserExtensionConfigFromJSON(jsonValue));
    }

    /**
     * Get the user extension configuration
     * Get the user extension configuration
     */
    async getUserExtensionConfig(requestParameters: GetUserExtensionConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserExtensionConfig> {
        const response = await this.getUserExtensionConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find the user by Twitch channel and return next streams from their teams
     * Get the user related schedule
     */
    async getUserRelatedScheduleRaw(requestParameters: GetUserRelatedScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserRelatedSchedule200Response>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getUserRelatedSchedule().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserRelatedSchedule().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/user-related-schedule/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserRelatedSchedule200ResponseFromJSON(jsonValue));
    }

    /**
     * Find the user by Twitch channel and return next streams from their teams
     * Get the user related schedule
     */
    async getUserRelatedSchedule(requestParameters: GetUserRelatedScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserRelatedSchedule200Response> {
        const response = await this.getUserRelatedScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find the user by Twitch channel and return their friends
     * Get the user relations
     */
    async getUserRelationsRaw(requestParameters: GetUserRelationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserRelations200Response>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getUserRelations().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserRelations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/user-relations/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserRelations200ResponseFromJSON(jsonValue));
    }

    /**
     * Find the user by Twitch channel and return their friends
     * Get the user relations
     */
    async getUserRelations(requestParameters: GetUserRelationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserRelations200Response> {
        const response = await this.getUserRelationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the use schedule
     * Get the users schedule
     */
    async getUserScheduleRaw(requestParameters: GetUserScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserScheduleSchema>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getUserSchedule().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserSchedule().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/user-schedule/{channelId}`.replace(`{${"channelId"}}`, encodeURIComponent(String(requestParameters['channelId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserScheduleSchemaFromJSON(jsonValue));
    }

    /**
     * Get the use schedule
     * Get the users schedule
     */
    async getUserSchedule(requestParameters: GetUserScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserScheduleSchema> {
        const response = await this.getUserScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the yogs schedule
     * Get the yogs schedule
     */
    async getYogsScheduleRaw(requestParameters: GetYogsScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<YogsScheduleSchema>> {
        if (requestParameters['channelId'] == null) {
            throw new runtime.RequiredError(
                'channelId',
                'Required parameter "channelId" was null or undefined when calling getYogsSchedule().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getYogsSchedule().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['channelId'] != null) {
            queryParameters['channelId'] = requestParameters['channelId'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/twitch-extension/yogs-schedule`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => YogsScheduleSchemaFromJSON(jsonValue));
    }

    /**
     * Get the yogs schedule
     * Get the yogs schedule
     */
    async getYogsSchedule(requestParameters: GetYogsScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<YogsScheduleSchema> {
        const response = await this.getYogsScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
