/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JJCause } from './JJCause';
import {
    JJCauseFromJSON,
    JJCauseFromJSONTyped,
    JJCauseToJSON,
} from './JJCause';

/**
 * 
 * @export
 * @interface CausesDisplaySchema
 */
export interface CausesDisplaySchema {
    /**
     * 
     * @type {number}
     * @memberof CausesDisplaySchema
     */
    count: number;
    /**
     * 
     * @type {Array<JJCause>}
     * @memberof CausesDisplaySchema
     */
    causes: Array<JJCause>;
}

/**
 * Check if a given object implements the CausesDisplaySchema interface.
 */
export function instanceOfCausesDisplaySchema(value: object): value is CausesDisplaySchema {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('causes' in value) || value['causes'] === undefined) return false;
    return true;
}

export function CausesDisplaySchemaFromJSON(json: any): CausesDisplaySchema {
    return CausesDisplaySchemaFromJSONTyped(json, false);
}

export function CausesDisplaySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CausesDisplaySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'causes': ((json['causes'] as Array<any>).map(JJCauseFromJSON)),
    };
}

export function CausesDisplaySchemaToJSON(value?: CausesDisplaySchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'causes': ((value['causes'] as Array<any>).map(JJCauseToJSON)),
    };
}

