/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrenciesSchema
 */
export interface CurrenciesSchema {
    /**
     * 
     * @type {number}
     * @memberof CurrenciesSchema
     */
    gbp: number;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesSchema
     */
    gbpFormatted: string;
    /**
     * 
     * @type {number}
     * @memberof CurrenciesSchema
     */
    usd: number;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesSchema
     */
    usdFormatted: string;
    /**
     * 
     * @type {number}
     * @memberof CurrenciesSchema
     */
    euro: number;
    /**
     * 
     * @type {string}
     * @memberof CurrenciesSchema
     */
    euroFormatted: string;
}

/**
 * Check if a given object implements the CurrenciesSchema interface.
 */
export function instanceOfCurrenciesSchema(value: object): value is CurrenciesSchema {
    if (!('gbp' in value) || value['gbp'] === undefined) return false;
    if (!('gbpFormatted' in value) || value['gbpFormatted'] === undefined) return false;
    if (!('usd' in value) || value['usd'] === undefined) return false;
    if (!('usdFormatted' in value) || value['usdFormatted'] === undefined) return false;
    if (!('euro' in value) || value['euro'] === undefined) return false;
    if (!('euroFormatted' in value) || value['euroFormatted'] === undefined) return false;
    return true;
}

export function CurrenciesSchemaFromJSON(json: any): CurrenciesSchema {
    return CurrenciesSchemaFromJSONTyped(json, false);
}

export function CurrenciesSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrenciesSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'gbp': json['gbp'],
        'gbpFormatted': json['gbpFormatted'],
        'usd': json['usd'],
        'usdFormatted': json['usdFormatted'],
        'euro': json['euro'],
        'euroFormatted': json['euroFormatted'],
    };
}

export function CurrenciesSchemaToJSON(value?: CurrenciesSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'gbp': value['gbp'],
        'gbpFormatted': value['gbpFormatted'],
        'usd': value['usd'],
        'usdFormatted': value['usdFormatted'],
        'euro': value['euro'],
        'euroFormatted': value['euroFormatted'],
    };
}

