/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtensionConfigRefreshInterval
 */
export interface ExtensionConfigRefreshInterval {
    /**
     * 
     * @type {number}
     * @memberof ExtensionConfigRefreshInterval
     */
    yogsSchedule: number;
    /**
     * 
     * @type {number}
     * @memberof ExtensionConfigRefreshInterval
     */
    charities: number;
    /**
     * 
     * @type {number}
     * @memberof ExtensionConfigRefreshInterval
     */
    fundraisers: number;
}

/**
 * Check if a given object implements the ExtensionConfigRefreshInterval interface.
 */
export function instanceOfExtensionConfigRefreshInterval(value: object): value is ExtensionConfigRefreshInterval {
    if (!('yogsSchedule' in value) || value['yogsSchedule'] === undefined) return false;
    if (!('charities' in value) || value['charities'] === undefined) return false;
    if (!('fundraisers' in value) || value['fundraisers'] === undefined) return false;
    return true;
}

export function ExtensionConfigRefreshIntervalFromJSON(json: any): ExtensionConfigRefreshInterval {
    return ExtensionConfigRefreshIntervalFromJSONTyped(json, false);
}

export function ExtensionConfigRefreshIntervalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensionConfigRefreshInterval {
    if (json == null) {
        return json;
    }
    return {
        
        'yogsSchedule': json['yogsSchedule'],
        'charities': json['charities'],
        'fundraisers': json['fundraisers'],
    };
}

export function ExtensionConfigRefreshIntervalToJSON(value?: ExtensionConfigRefreshInterval | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'yogsSchedule': value['yogsSchedule'],
        'charities': value['charities'],
        'fundraisers': value['fundraisers'],
    };
}

