/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtensionConfigRefreshInterval } from './ExtensionConfigRefreshInterval';
import {
    ExtensionConfigRefreshIntervalFromJSON,
    ExtensionConfigRefreshIntervalFromJSONTyped,
    ExtensionConfigRefreshIntervalToJSON,
} from './ExtensionConfigRefreshInterval';
import type { ExtensionConfigDonationLink } from './ExtensionConfigDonationLink';
import {
    ExtensionConfigDonationLinkFromJSON,
    ExtensionConfigDonationLinkFromJSONTyped,
    ExtensionConfigDonationLinkToJSON,
} from './ExtensionConfigDonationLink';

/**
 * 
 * @export
 * @interface ExtensionConfig
 */
export interface ExtensionConfig {
    /**
     * 
     * @type {number}
     * @memberof ExtensionConfig
     */
    year: number;
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionConfig
     */
    showYogsSchedule: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionConfig
     */
    showCharities: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionConfig
     */
    showFundraisers: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionConfig
     */
    showUserFundraiser: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionConfig
     */
    showUserSchedule: boolean;
    /**
     * 
     * @type {ExtensionConfigRefreshInterval}
     * @memberof ExtensionConfig
     */
    refreshInterval: ExtensionConfigRefreshInterval;
    /**
     * 
     * @type {ExtensionConfigDonationLink}
     * @memberof ExtensionConfig
     */
    donationLink: ExtensionConfigDonationLink;
    /**
     * 
     * @type {string}
     * @memberof ExtensionConfig
     */
    donationTrackerUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ExtensionConfig
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ExtensionConfig interface.
 */
export function instanceOfExtensionConfig(value: object): value is ExtensionConfig {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('showYogsSchedule' in value) || value['showYogsSchedule'] === undefined) return false;
    if (!('showCharities' in value) || value['showCharities'] === undefined) return false;
    if (!('showFundraisers' in value) || value['showFundraisers'] === undefined) return false;
    if (!('showUserFundraiser' in value) || value['showUserFundraiser'] === undefined) return false;
    if (!('showUserSchedule' in value) || value['showUserSchedule'] === undefined) return false;
    if (!('refreshInterval' in value) || value['refreshInterval'] === undefined) return false;
    if (!('donationLink' in value) || value['donationLink'] === undefined) return false;
    if (!('donationTrackerUrl' in value) || value['donationTrackerUrl'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ExtensionConfigFromJSON(json: any): ExtensionConfig {
    return ExtensionConfigFromJSONTyped(json, false);
}

export function ExtensionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'showYogsSchedule': json['showYogsSchedule'],
        'showCharities': json['showCharities'],
        'showFundraisers': json['showFundraisers'],
        'showUserFundraiser': json['showUserFundraiser'],
        'showUserSchedule': json['showUserSchedule'],
        'refreshInterval': ExtensionConfigRefreshIntervalFromJSON(json['refreshInterval']),
        'donationLink': ExtensionConfigDonationLinkFromJSON(json['donationLink']),
        'donationTrackerUrl': json['donationTrackerUrl'],
        'timestamp': json['timestamp'],
    };
}

export function ExtensionConfigToJSON(value?: ExtensionConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'year': value['year'],
        'showYogsSchedule': value['showYogsSchedule'],
        'showCharities': value['showCharities'],
        'showFundraisers': value['showFundraisers'],
        'showUserFundraiser': value['showUserFundraiser'],
        'showUserSchedule': value['showUserSchedule'],
        'refreshInterval': ExtensionConfigRefreshIntervalToJSON(value['refreshInterval']),
        'donationLink': ExtensionConfigDonationLinkToJSON(value['donationLink']),
        'donationTrackerUrl': value['donationTrackerUrl'],
        'timestamp': value['timestamp'],
    };
}

