/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtensionConfigDonationLink
 */
export interface ExtensionConfigDonationLink {
    /**
     * 
     * @type {string}
     * @memberof ExtensionConfigDonationLink
     */
    url: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExtensionConfigDonationLink
     */
    visible: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExtensionConfigDonationLink
     */
    text: string;
}

/**
 * Check if a given object implements the ExtensionConfigDonationLink interface.
 */
export function instanceOfExtensionConfigDonationLink(value: object): value is ExtensionConfigDonationLink {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('visible' in value) || value['visible'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function ExtensionConfigDonationLinkFromJSON(json: any): ExtensionConfigDonationLink {
    return ExtensionConfigDonationLinkFromJSONTyped(json, false);
}

export function ExtensionConfigDonationLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensionConfigDonationLink {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'visible': json['visible'],
        'text': json['text'],
    };
}

export function ExtensionConfigDonationLinkToJSON(value?: ExtensionConfigDonationLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'visible': value['visible'],
        'text': value['text'],
    };
}

