/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JJCause } from './JJCause';
import {
    JJCauseFromJSON,
    JJCauseFromJSONTyped,
    JJCauseToJSON,
} from './JJCause';
import type { OverviewSchema } from './OverviewSchema';
import {
    OverviewSchemaFromJSON,
    OverviewSchemaFromJSONTyped,
    OverviewSchemaToJSON,
} from './OverviewSchema';

/**
 * 
 * @export
 * @interface GetCauses200Response
 */
export interface GetCauses200Response {
    /**
     * 
     * @type {number}
     * @memberof GetCauses200Response
     */
    count: number;
    /**
     * 
     * @type {Array<JJCause>}
     * @memberof GetCauses200Response
     */
    list: Array<JJCause>;
    /**
     * 
     * @type {OverviewSchema}
     * @memberof GetCauses200Response
     */
    overview: OverviewSchema;
}

/**
 * Check if a given object implements the GetCauses200Response interface.
 */
export function instanceOfGetCauses200Response(value: object): value is GetCauses200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('list' in value) || value['list'] === undefined) return false;
    if (!('overview' in value) || value['overview'] === undefined) return false;
    return true;
}

export function GetCauses200ResponseFromJSON(json: any): GetCauses200Response {
    return GetCauses200ResponseFromJSONTyped(json, false);
}

export function GetCauses200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCauses200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'list': ((json['list'] as Array<any>).map(JJCauseFromJSON)),
        'overview': OverviewSchemaFromJSON(json['overview']),
    };
}

export function GetCauses200ResponseToJSON(value?: GetCauses200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'list': ((value['list'] as Array<any>).map(JJCauseToJSON)),
        'overview': OverviewSchemaToJSON(value['overview']),
    };
}

