/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCauses200ResponseListInnerRaised } from './GetCauses200ResponseListInnerRaised';
import {
    GetCauses200ResponseListInnerRaisedFromJSON,
    GetCauses200ResponseListInnerRaisedFromJSONTyped,
    GetCauses200ResponseListInnerRaisedToJSON,
} from './GetCauses200ResponseListInnerRaised';

/**
 * 
 * @export
 * @interface GetCauses200ResponseListInner
 */
export interface GetCauses200ResponseListInner {
    /**
     * 
     * @type {number}
     * @memberof GetCauses200ResponseListInner
     */
    id: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetCauses200ResponseListInner
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCauses200ResponseListInner
     */
    logo: string;
    /**
     * 
     * @type {string}
     * @memberof GetCauses200ResponseListInner
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCauses200ResponseListInner
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GetCauses200ResponseListInner
     */
    donateUrl: string;
    /**
     * 
     * @type {GetCauses200ResponseListInnerRaised}
     * @memberof GetCauses200ResponseListInner
     */
    raised: GetCauses200ResponseListInnerRaised;
}

/**
 * Check if a given object implements the GetCauses200ResponseListInner interface.
 */
export function instanceOfGetCauses200ResponseListInner(value: object): value is GetCauses200ResponseListInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('logo' in value) || value['logo'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('donateUrl' in value) || value['donateUrl'] === undefined) return false;
    if (!('raised' in value) || value['raised'] === undefined) return false;
    return true;
}

export function GetCauses200ResponseListInnerFromJSON(json: any): GetCauses200ResponseListInner {
    return GetCauses200ResponseListInnerFromJSONTyped(json, false);
}

export function GetCauses200ResponseListInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCauses200ResponseListInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'logo': json['logo'],
        'description': json['description'],
        'url': json['url'],
        'donateUrl': json['donateUrl'],
        'raised': GetCauses200ResponseListInnerRaisedFromJSON(json['raised']),
    };
}

export function GetCauses200ResponseListInnerToJSON(value?: GetCauses200ResponseListInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'logo': value['logo'],
        'description': value['description'],
        'url': value['url'],
        'donateUrl': value['donateUrl'],
        'raised': GetCauses200ResponseListInnerRaisedToJSON(value['raised']),
    };
}

