/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCampaigns200ResponseListInnerUser } from './GetCampaigns200ResponseListInnerUser';
import {
    GetCampaigns200ResponseListInnerUserFromJSON,
    GetCampaigns200ResponseListInnerUserFromJSONTyped,
    GetCampaigns200ResponseListInnerUserToJSON,
} from './GetCampaigns200ResponseListInnerUser';
import type { GetCampaigns200ResponseListInnerLivestream } from './GetCampaigns200ResponseListInnerLivestream';
import {
    GetCampaigns200ResponseListInnerLivestreamFromJSON,
    GetCampaigns200ResponseListInnerLivestreamFromJSONTyped,
    GetCampaigns200ResponseListInnerLivestreamToJSON,
} from './GetCampaigns200ResponseListInnerLivestream';

/**
 * 
 * @export
 * @interface GetCampaigns200ResponseListInner
 */
export interface GetCampaigns200ResponseListInner {
    /**
     * 
     * @type {number}
     * @memberof GetCampaigns200ResponseListInner
     */
    causeId: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInner
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInner
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInner
     */
    slug: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInner
     */
    url: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInner
     */
    startTime: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetCampaigns200ResponseListInner
     */
    raised: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetCampaigns200ResponseListInner
     */
    goal: number | null;
    /**
     * 
     * @type {GetCampaigns200ResponseListInnerLivestream}
     * @memberof GetCampaigns200ResponseListInner
     */
    livestream: GetCampaigns200ResponseListInnerLivestream;
    /**
     * 
     * @type {GetCampaigns200ResponseListInnerUser}
     * @memberof GetCampaigns200ResponseListInner
     */
    user: GetCampaigns200ResponseListInnerUser;
}

/**
 * Check if a given object implements the GetCampaigns200ResponseListInner interface.
 */
export function instanceOfGetCampaigns200ResponseListInner(value: object): value is GetCampaigns200ResponseListInner {
    if (!('causeId' in value) || value['causeId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('raised' in value) || value['raised'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('livestream' in value) || value['livestream'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function GetCampaigns200ResponseListInnerFromJSON(json: any): GetCampaigns200ResponseListInner {
    return GetCampaigns200ResponseListInnerFromJSONTyped(json, false);
}

export function GetCampaigns200ResponseListInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCampaigns200ResponseListInner {
    if (json == null) {
        return json;
    }
    return {
        
        'causeId': json['causeId'],
        'name': json['name'],
        'description': json['description'],
        'slug': json['slug'],
        'url': json['url'],
        'startTime': json['startTime'],
        'raised': json['raised'],
        'goal': json['goal'],
        'livestream': GetCampaigns200ResponseListInnerLivestreamFromJSON(json['livestream']),
        'user': GetCampaigns200ResponseListInnerUserFromJSON(json['user']),
    };
}

export function GetCampaigns200ResponseListInnerToJSON(value?: GetCampaigns200ResponseListInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'causeId': value['causeId'],
        'name': value['name'],
        'description': value['description'],
        'slug': value['slug'],
        'url': value['url'],
        'startTime': value['startTime'],
        'raised': value['raised'],
        'goal': value['goal'],
        'livestream': GetCampaigns200ResponseListInnerLivestreamToJSON(value['livestream']),
        'user': GetCampaigns200ResponseListInnerUserToJSON(value['user']),
    };
}

