/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCampaignsTwitchParameter
 */
export interface GetCampaignsTwitchParameter {
    /**
     * 
     * @type {string}
     * @memberof GetCampaignsTwitchParameter
     */
    channelId: string;
    /**
     * 
     * @type {string}
     * @memberof GetCampaignsTwitchParameter
     */
    userId: string;
}

/**
 * Check if a given object implements the GetCampaignsTwitchParameter interface.
 */
export function instanceOfGetCampaignsTwitchParameter(value: object): value is GetCampaignsTwitchParameter {
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function GetCampaignsTwitchParameterFromJSON(json: any): GetCampaignsTwitchParameter {
    return GetCampaignsTwitchParameterFromJSONTyped(json, false);
}

export function GetCampaignsTwitchParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCampaignsTwitchParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'userId': json['userId'],
    };
}

export function GetCampaignsTwitchParameterToJSON(value?: GetCampaignsTwitchParameter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'channelId': value['channelId'],
        'userId': value['userId'],
    };
}

