/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCauses200ResponseListInnerRaised
 */
export interface GetCauses200ResponseListInnerRaised {
    /**
     * 
     * @type {number}
     * @memberof GetCauses200ResponseListInnerRaised
     */
    yogscast: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetCauses200ResponseListInnerRaised
     */
    fundraisers: number | null;
}

/**
 * Check if a given object implements the GetCauses200ResponseListInnerRaised interface.
 */
export function instanceOfGetCauses200ResponseListInnerRaised(value: object): value is GetCauses200ResponseListInnerRaised {
    if (!('yogscast' in value) || value['yogscast'] === undefined) return false;
    if (!('fundraisers' in value) || value['fundraisers'] === undefined) return false;
    return true;
}

export function GetCauses200ResponseListInnerRaisedFromJSON(json: any): GetCauses200ResponseListInnerRaised {
    return GetCauses200ResponseListInnerRaisedFromJSONTyped(json, false);
}

export function GetCauses200ResponseListInnerRaisedFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCauses200ResponseListInnerRaised {
    if (json == null) {
        return json;
    }
    return {
        
        'yogscast': json['yogscast'],
        'fundraisers': json['fundraisers'],
    };
}

export function GetCauses200ResponseListInnerRaisedToJSON(value?: GetCauses200ResponseListInnerRaised | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'yogscast': value['yogscast'],
        'fundraisers': value['fundraisers'],
    };
}

