/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCampaigns200ResponseListInner } from './GetCampaigns200ResponseListInner';
import {
    GetCampaigns200ResponseListInnerFromJSON,
    GetCampaigns200ResponseListInnerFromJSONTyped,
    GetCampaigns200ResponseListInnerToJSON,
} from './GetCampaigns200ResponseListInner';

/**
 * 
 * @export
 * @interface GetCampaigns200Response
 */
export interface GetCampaigns200Response {
    /**
     * 
     * @type {number}
     * @memberof GetCampaigns200Response
     */
    count: number | null;
    /**
     * 
     * @type {Array<GetCampaigns200ResponseListInner>}
     * @memberof GetCampaigns200Response
     */
    list: Array<GetCampaigns200ResponseListInner>;
}

/**
 * Check if a given object implements the GetCampaigns200Response interface.
 */
export function instanceOfGetCampaigns200Response(value: object): value is GetCampaigns200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('list' in value) || value['list'] === undefined) return false;
    return true;
}

export function GetCampaigns200ResponseFromJSON(json: any): GetCampaigns200Response {
    return GetCampaigns200ResponseFromJSONTyped(json, false);
}

export function GetCampaigns200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCampaigns200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'list': ((json['list'] as Array<any>).map(GetCampaigns200ResponseListInnerFromJSON)),
    };
}

export function GetCampaigns200ResponseToJSON(value?: GetCampaigns200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'list': ((value['list'] as Array<any>).map(GetCampaigns200ResponseListInnerToJSON)),
    };
}

