/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCampaigns200ResponseListInnerUser
 */
export interface GetCampaigns200ResponseListInnerUser {
    /**
     * 
     * @type {number}
     * @memberof GetCampaigns200ResponseListInnerUser
     */
    id: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInnerUser
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInnerUser
     */
    slug: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInnerUser
     */
    avatar: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInnerUser
     */
    url: string | null;
}

/**
 * Check if a given object implements the GetCampaigns200ResponseListInnerUser interface.
 */
export function instanceOfGetCampaigns200ResponseListInnerUser(value: object): value is GetCampaigns200ResponseListInnerUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function GetCampaigns200ResponseListInnerUserFromJSON(json: any): GetCampaigns200ResponseListInnerUser {
    return GetCampaigns200ResponseListInnerUserFromJSONTyped(json, false);
}

export function GetCampaigns200ResponseListInnerUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCampaigns200ResponseListInnerUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'avatar': json['avatar'],
        'url': json['url'],
    };
}

export function GetCampaigns200ResponseListInnerUserToJSON(value?: GetCampaigns200ResponseListInnerUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'avatar': value['avatar'],
        'url': value['url'],
    };
}

