/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCampaigns200ResponseListInnerLivestream
 */
export interface GetCampaigns200ResponseListInnerLivestream {
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInnerLivestream
     */
    channel: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCampaigns200ResponseListInnerLivestream
     */
    type: string | null;
}

/**
 * Check if a given object implements the GetCampaigns200ResponseListInnerLivestream interface.
 */
export function instanceOfGetCampaigns200ResponseListInnerLivestream(value: object): value is GetCampaigns200ResponseListInnerLivestream {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GetCampaigns200ResponseListInnerLivestreamFromJSON(json: any): GetCampaigns200ResponseListInnerLivestream {
    return GetCampaigns200ResponseListInnerLivestreamFromJSONTyped(json, false);
}

export function GetCampaigns200ResponseListInnerLivestreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCampaigns200ResponseListInnerLivestream {
    if (json == null) {
        return json;
    }
    return {
        
        'channel': json['channel'],
        'type': json['type'],
    };
}

export function GetCampaigns200ResponseListInnerLivestreamToJSON(value?: GetCampaigns200ResponseListInnerLivestream | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'channel': value['channel'],
        'type': value['type'],
    };
}

