/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetExtensionConfig200ResponseRefreshInterval
 */
export interface GetExtensionConfig200ResponseRefreshInterval {
    /**
     * 
     * @type {number}
     * @memberof GetExtensionConfig200ResponseRefreshInterval
     */
    yogsSchedule: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetExtensionConfig200ResponseRefreshInterval
     */
    charities: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetExtensionConfig200ResponseRefreshInterval
     */
    fundraisers: number | null;
}

/**
 * Check if a given object implements the GetExtensionConfig200ResponseRefreshInterval interface.
 */
export function instanceOfGetExtensionConfig200ResponseRefreshInterval(value: object): value is GetExtensionConfig200ResponseRefreshInterval {
    if (!('yogsSchedule' in value) || value['yogsSchedule'] === undefined) return false;
    if (!('charities' in value) || value['charities'] === undefined) return false;
    if (!('fundraisers' in value) || value['fundraisers'] === undefined) return false;
    return true;
}

export function GetExtensionConfig200ResponseRefreshIntervalFromJSON(json: any): GetExtensionConfig200ResponseRefreshInterval {
    return GetExtensionConfig200ResponseRefreshIntervalFromJSONTyped(json, false);
}

export function GetExtensionConfig200ResponseRefreshIntervalFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExtensionConfig200ResponseRefreshInterval {
    if (json == null) {
        return json;
    }
    return {
        
        'yogsSchedule': json['yogsSchedule'],
        'charities': json['charities'],
        'fundraisers': json['fundraisers'],
    };
}

export function GetExtensionConfig200ResponseRefreshIntervalToJSON(value?: GetExtensionConfig200ResponseRefreshInterval | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'yogsSchedule': value['yogsSchedule'],
        'charities': value['charities'],
        'fundraisers': value['fundraisers'],
    };
}

