/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetExtensionConfigTwitchParameter
 */
export interface GetExtensionConfigTwitchParameter {
    /**
     * 
     * @type {string}
     * @memberof GetExtensionConfigTwitchParameter
     */
    channelId: string;
    /**
     * 
     * @type {string}
     * @memberof GetExtensionConfigTwitchParameter
     */
    userId: string | null;
}

/**
 * Check if a given object implements the GetExtensionConfigTwitchParameter interface.
 */
export function instanceOfGetExtensionConfigTwitchParameter(value: object): value is GetExtensionConfigTwitchParameter {
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function GetExtensionConfigTwitchParameterFromJSON(json: any): GetExtensionConfigTwitchParameter {
    return GetExtensionConfigTwitchParameterFromJSONTyped(json, false);
}

export function GetExtensionConfigTwitchParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExtensionConfigTwitchParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channelId'],
        'userId': json['userId'],
    };
}

export function GetExtensionConfigTwitchParameterToJSON(value?: GetExtensionConfigTwitchParameter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'channelId': value['channelId'],
        'userId': value['userId'],
    };
}

