/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetExtensionConfig200ResponseDonationLink } from './GetExtensionConfig200ResponseDonationLink';
import {
    GetExtensionConfig200ResponseDonationLinkFromJSON,
    GetExtensionConfig200ResponseDonationLinkFromJSONTyped,
    GetExtensionConfig200ResponseDonationLinkToJSON,
} from './GetExtensionConfig200ResponseDonationLink';
import type { GetExtensionConfig200ResponseRefreshInterval } from './GetExtensionConfig200ResponseRefreshInterval';
import {
    GetExtensionConfig200ResponseRefreshIntervalFromJSON,
    GetExtensionConfig200ResponseRefreshIntervalFromJSONTyped,
    GetExtensionConfig200ResponseRefreshIntervalToJSON,
} from './GetExtensionConfig200ResponseRefreshInterval';

/**
 * 
 * @export
 * @interface GetExtensionConfig200Response
 */
export interface GetExtensionConfig200Response {
    /**
     * 
     * @type {number}
     * @memberof GetExtensionConfig200Response
     */
    year: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetExtensionConfig200Response
     */
    showYogsSchedule: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetExtensionConfig200Response
     */
    showCharities: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetExtensionConfig200Response
     */
    showFundraisers: boolean;
    /**
     * 
     * @type {GetExtensionConfig200ResponseRefreshInterval}
     * @memberof GetExtensionConfig200Response
     */
    refreshInterval: GetExtensionConfig200ResponseRefreshInterval;
    /**
     * 
     * @type {GetExtensionConfig200ResponseDonationLink}
     * @memberof GetExtensionConfig200Response
     */
    donationLink: GetExtensionConfig200ResponseDonationLink;
    /**
     * 
     * @type {string}
     * @memberof GetExtensionConfig200Response
     */
    donationTrackerUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetExtensionConfig200Response
     */
    timestamp: string | null;
}

/**
 * Check if a given object implements the GetExtensionConfig200Response interface.
 */
export function instanceOfGetExtensionConfig200Response(value: object): value is GetExtensionConfig200Response {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('showYogsSchedule' in value) || value['showYogsSchedule'] === undefined) return false;
    if (!('showCharities' in value) || value['showCharities'] === undefined) return false;
    if (!('showFundraisers' in value) || value['showFundraisers'] === undefined) return false;
    if (!('refreshInterval' in value) || value['refreshInterval'] === undefined) return false;
    if (!('donationLink' in value) || value['donationLink'] === undefined) return false;
    if (!('donationTrackerUrl' in value) || value['donationTrackerUrl'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function GetExtensionConfig200ResponseFromJSON(json: any): GetExtensionConfig200Response {
    return GetExtensionConfig200ResponseFromJSONTyped(json, false);
}

export function GetExtensionConfig200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExtensionConfig200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'showYogsSchedule': json['showYogsSchedule'],
        'showCharities': json['showCharities'],
        'showFundraisers': json['showFundraisers'],
        'refreshInterval': GetExtensionConfig200ResponseRefreshIntervalFromJSON(json['refreshInterval']),
        'donationLink': GetExtensionConfig200ResponseDonationLinkFromJSON(json['donationLink']),
        'donationTrackerUrl': json['donationTrackerUrl'],
        'timestamp': json['timestamp'],
    };
}

export function GetExtensionConfig200ResponseToJSON(value?: GetExtensionConfig200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'year': value['year'],
        'showYogsSchedule': value['showYogsSchedule'],
        'showCharities': value['showCharities'],
        'showFundraisers': value['showFundraisers'],
        'refreshInterval': GetExtensionConfig200ResponseRefreshIntervalToJSON(value['refreshInterval']),
        'donationLink': GetExtensionConfig200ResponseDonationLinkToJSON(value['donationLink']),
        'donationTrackerUrl': value['donationTrackerUrl'],
        'timestamp': value['timestamp'],
    };
}

