/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetExtensionConfig200ResponseDonationLink
 */
export interface GetExtensionConfig200ResponseDonationLink {
    /**
     * 
     * @type {string}
     * @memberof GetExtensionConfig200ResponseDonationLink
     */
    url: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetExtensionConfig200ResponseDonationLink
     */
    visible: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetExtensionConfig200ResponseDonationLink
     */
    text: string | null;
}

/**
 * Check if a given object implements the GetExtensionConfig200ResponseDonationLink interface.
 */
export function instanceOfGetExtensionConfig200ResponseDonationLink(value: object): value is GetExtensionConfig200ResponseDonationLink {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('visible' in value) || value['visible'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function GetExtensionConfig200ResponseDonationLinkFromJSON(json: any): GetExtensionConfig200ResponseDonationLink {
    return GetExtensionConfig200ResponseDonationLinkFromJSONTyped(json, false);
}

export function GetExtensionConfig200ResponseDonationLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExtensionConfig200ResponseDonationLink {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'visible': json['visible'],
        'text': json['text'],
    };
}

export function GetExtensionConfig200ResponseDonationLinkToJSON(value?: GetExtensionConfig200ResponseDonationLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'visible': value['visible'],
        'text': value['text'],
    };
}

