/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUserRelatedSchedule200ResponseTeams } from './GetUserRelatedSchedule200ResponseTeams';
import {
    GetUserRelatedSchedule200ResponseTeamsFromJSON,
    GetUserRelatedSchedule200ResponseTeamsFromJSONTyped,
    GetUserRelatedSchedule200ResponseTeamsToJSON,
} from './GetUserRelatedSchedule200ResponseTeams';

/**
 * 
 * @export
 * @interface GetUserRelatedSchedule200Response
 */
export interface GetUserRelatedSchedule200Response {
    /**
     * 
     * @type {GetUserRelatedSchedule200ResponseTeams}
     * @memberof GetUserRelatedSchedule200Response
     */
    teams: GetUserRelatedSchedule200ResponseTeams;
}

/**
 * Check if a given object implements the GetUserRelatedSchedule200Response interface.
 */
export function instanceOfGetUserRelatedSchedule200Response(value: object): value is GetUserRelatedSchedule200Response {
    if (!('teams' in value) || value['teams'] === undefined) return false;
    return true;
}

export function GetUserRelatedSchedule200ResponseFromJSON(json: any): GetUserRelatedSchedule200Response {
    return GetUserRelatedSchedule200ResponseFromJSONTyped(json, false);
}

export function GetUserRelatedSchedule200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserRelatedSchedule200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'teams': GetUserRelatedSchedule200ResponseTeamsFromJSON(json['teams']),
    };
}

export function GetUserRelatedSchedule200ResponseToJSON(value?: GetUserRelatedSchedule200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teams': GetUserRelatedSchedule200ResponseTeamsToJSON(value['teams']),
    };
}

