/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserExtensionConfig200Response
 */
export interface GetUserExtensionConfig200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetUserExtensionConfig200Response
     */
    hasCampaign: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetUserExtensionConfig200Response
     */
    hasSchedule: boolean;
}

/**
 * Check if a given object implements the GetUserExtensionConfig200Response interface.
 */
export function instanceOfGetUserExtensionConfig200Response(value: object): value is GetUserExtensionConfig200Response {
    if (!('hasCampaign' in value) || value['hasCampaign'] === undefined) return false;
    if (!('hasSchedule' in value) || value['hasSchedule'] === undefined) return false;
    return true;
}

export function GetUserExtensionConfig200ResponseFromJSON(json: any): GetUserExtensionConfig200Response {
    return GetUserExtensionConfig200ResponseFromJSONTyped(json, false);
}

export function GetUserExtensionConfig200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserExtensionConfig200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'hasCampaign': json['hasCampaign'],
        'hasSchedule': json['hasSchedule'],
    };
}

export function GetUserExtensionConfig200ResponseToJSON(value?: GetUserExtensionConfig200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hasCampaign': value['hasCampaign'],
        'hasSchedule': value['hasSchedule'],
    };
}
