/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserData200ResponseUser
 */
export interface GetUserData200ResponseUser {
    /**
     * 
     * @type {number}
     * @memberof GetUserData200ResponseUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200ResponseUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200ResponseUser
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200ResponseUser
     */
    avatar: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200ResponseUser
     */
    url: string;
}

/**
 * Check if a given object implements the GetUserData200ResponseUser interface.
 */
export function instanceOfGetUserData200ResponseUser(value: object): value is GetUserData200ResponseUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function GetUserData200ResponseUserFromJSON(json: any): GetUserData200ResponseUser {
    return GetUserData200ResponseUserFromJSONTyped(json, false);
}

export function GetUserData200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserData200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'avatar': json['avatar'],
        'url': json['url'],
    };
}

export function GetUserData200ResponseUserToJSON(value?: GetUserData200ResponseUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'avatar': value['avatar'],
        'url': value['url'],
    };
}

