/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUserData200ResponseUser } from './GetUserData200ResponseUser';
import {
    GetUserData200ResponseUserFromJSON,
    GetUserData200ResponseUserFromJSONTyped,
    GetUserData200ResponseUserToJSON,
} from './GetUserData200ResponseUser';
import type { GetUserData200ResponseLivestream } from './GetUserData200ResponseLivestream';
import {
    GetUserData200ResponseLivestreamFromJSON,
    GetUserData200ResponseLivestreamFromJSONTyped,
    GetUserData200ResponseLivestreamToJSON,
} from './GetUserData200ResponseLivestream';

/**
 * 
 * @export
 * @interface GetUserData200Response
 */
export interface GetUserData200Response {
    /**
     * 
     * @type {number}
     * @memberof GetUserData200Response
     */
    causeId: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200Response
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200Response
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200Response
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200Response
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200Response
     */
    startTime: string;
    /**
     * 
     * @type {number}
     * @memberof GetUserData200Response
     */
    raised: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserData200Response
     */
    goal: number;
    /**
     * 
     * @type {GetUserData200ResponseLivestream}
     * @memberof GetUserData200Response
     */
    livestream: GetUserData200ResponseLivestream;
    /**
     * 
     * @type {GetUserData200ResponseUser}
     * @memberof GetUserData200Response
     */
    user: GetUserData200ResponseUser;
}

/**
 * Check if a given object implements the GetUserData200Response interface.
 */
export function instanceOfGetUserData200Response(value: object): value is GetUserData200Response {
    if (!('causeId' in value) || value['causeId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('raised' in value) || value['raised'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('livestream' in value) || value['livestream'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function GetUserData200ResponseFromJSON(json: any): GetUserData200Response {
    return GetUserData200ResponseFromJSONTyped(json, false);
}

export function GetUserData200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserData200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'causeId': json['causeId'],
        'name': json['name'],
        'description': json['description'],
        'slug': json['slug'],
        'url': json['url'],
        'startTime': json['startTime'],
        'raised': json['raised'],
        'goal': json['goal'],
        'livestream': GetUserData200ResponseLivestreamFromJSON(json['livestream']),
        'user': GetUserData200ResponseUserFromJSON(json['user']),
    };
}

export function GetUserData200ResponseToJSON(value?: GetUserData200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'causeId': value['causeId'],
        'name': value['name'],
        'description': value['description'],
        'slug': value['slug'],
        'url': value['url'],
        'startTime': value['startTime'],
        'raised': value['raised'],
        'goal': value['goal'],
        'livestream': GetUserData200ResponseLivestreamToJSON(value['livestream']),
        'user': GetUserData200ResponseUserToJSON(value['user']),
    };
}

