/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDisplay } from './UserDisplay';
import {
    UserDisplayFromJSON,
    UserDisplayFromJSONTyped,
    UserDisplayToJSON,
} from './UserDisplay';

/**
 * 
 * @export
 * @interface GetUserRelations200Response
 */
export interface GetUserRelations200Response {
    /**
     * 
     * @type {Array<UserDisplay>}
     * @memberof GetUserRelations200Response
     */
    friends: Array<UserDisplay>;
}

/**
 * Check if a given object implements the GetUserRelations200Response interface.
 */
export function instanceOfGetUserRelations200Response(value: object): value is GetUserRelations200Response {
    if (!('friends' in value) || value['friends'] === undefined) return false;
    return true;
}

export function GetUserRelations200ResponseFromJSON(json: any): GetUserRelations200Response {
    return GetUserRelations200ResponseFromJSONTyped(json, false);
}

export function GetUserRelations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserRelations200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'friends': ((json['friends'] as Array<any>).map(UserDisplayFromJSON)),
    };
}

export function GetUserRelations200ResponseToJSON(value?: GetUserRelations200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'friends': ((value['friends'] as Array<any>).map(UserDisplayToJSON)),
    };
}

