/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JJCampaign } from './JJCampaign';
import {
    JJCampaignFromJSON,
    JJCampaignFromJSONTyped,
    JJCampaignToJSON,
} from './JJCampaign';
import type { JJCause } from './JJCause';
import {
    JJCauseFromJSON,
    JJCauseFromJSONTyped,
    JJCauseToJSON,
} from './JJCause';

/**
 * 
 * @export
 * @interface GetUserData200Response
 */
export interface GetUserData200Response {
    /**
     * 
     * @type {JJCampaign}
     * @memberof GetUserData200Response
     */
    campaign: JJCampaign;
    /**
     * 
     * @type {JJCause}
     * @memberof GetUserData200Response
     */
    cause?: JJCause;
}

/**
 * Check if a given object implements the GetUserData200Response interface.
 */
export function instanceOfGetUserData200Response(value: object): value is GetUserData200Response {
    if (!('campaign' in value) || value['campaign'] === undefined) return false;
    return true;
}

export function GetUserData200ResponseFromJSON(json: any): GetUserData200Response {
    return GetUserData200ResponseFromJSONTyped(json, false);
}

export function GetUserData200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserData200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'campaign': JJCampaignFromJSON(json['campaign']),
        'cause': json['cause'] == null ? undefined : JJCauseFromJSON(json['cause']),
    };
}

export function GetUserData200ResponseToJSON(value?: GetUserData200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'campaign': JJCampaignToJSON(value['campaign']),
        'cause': JJCauseToJSON(value['cause']),
    };
}

