/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stream } from './Stream';
import {
    StreamFromJSON,
    StreamFromJSONTyped,
    StreamToJSON,
} from './Stream';

/**
 * 
 * @export
 * @interface GetUserRelatedSchedule200ResponseTeams
 */
export interface GetUserRelatedSchedule200ResponseTeams {
    /**
     * 
     * @type {Array<Stream>}
     * @memberof GetUserRelatedSchedule200ResponseTeams
     */
    streams: Array<Stream>;
}

/**
 * Check if a given object implements the GetUserRelatedSchedule200ResponseTeams interface.
 */
export function instanceOfGetUserRelatedSchedule200ResponseTeams(value: object): value is GetUserRelatedSchedule200ResponseTeams {
    if (!('streams' in value) || value['streams'] === undefined) return false;
    return true;
}

export function GetUserRelatedSchedule200ResponseTeamsFromJSON(json: any): GetUserRelatedSchedule200ResponseTeams {
    return GetUserRelatedSchedule200ResponseTeamsFromJSONTyped(json, false);
}

export function GetUserRelatedSchedule200ResponseTeamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserRelatedSchedule200ResponseTeams {
    if (json == null) {
        return json;
    }
    return {
        
        'streams': ((json['streams'] as Array<any>).map(StreamFromJSON)),
    };
}

export function GetUserRelatedSchedule200ResponseTeamsToJSON(value?: GetUserRelatedSchedule200ResponseTeams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'streams': ((value['streams'] as Array<any>).map(StreamToJSON)),
    };
}

