/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserData200ResponseLivestream
 */
export interface GetUserData200ResponseLivestream {
    /**
     * 
     * @type {string}
     * @memberof GetUserData200ResponseLivestream
     */
    channel: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserData200ResponseLivestream
     */
    type: string;
}

/**
 * Check if a given object implements the GetUserData200ResponseLivestream interface.
 */
export function instanceOfGetUserData200ResponseLivestream(value: object): value is GetUserData200ResponseLivestream {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GetUserData200ResponseLivestreamFromJSON(json: any): GetUserData200ResponseLivestream {
    return GetUserData200ResponseLivestreamFromJSONTyped(json, false);
}

export function GetUserData200ResponseLivestreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserData200ResponseLivestream {
    if (json == null) {
        return json;
    }
    return {
        
        'channel': json['channel'],
        'type': json['type'],
    };
}

export function GetUserData200ResponseLivestreamToJSON(value?: GetUserData200ResponseLivestream | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'channel': value['channel'],
        'type': value['type'],
    };
}

