/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetYogsSchedule200ResponseStreamsInner } from './GetYogsSchedule200ResponseStreamsInner';
import {
    GetYogsSchedule200ResponseStreamsInnerFromJSON,
    GetYogsSchedule200ResponseStreamsInnerFromJSONTyped,
    GetYogsSchedule200ResponseStreamsInnerToJSON,
} from './GetYogsSchedule200ResponseStreamsInner';

/**
 * 
 * @export
 * @interface GetUserSchedule200Response
 */
export interface GetUserSchedule200Response {
    /**
     * 
     * @type {Date}
     * @memberof GetUserSchedule200Response
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetUserSchedule200Response
     */
    end: Date;
    /**
     * 
     * @type {Array<GetYogsSchedule200ResponseStreamsInner>}
     * @memberof GetUserSchedule200Response
     */
    streams: Array<GetYogsSchedule200ResponseStreamsInner>;
}

/**
 * Check if a given object implements the GetUserSchedule200Response interface.
 */
export function instanceOfGetUserSchedule200Response(value: object): value is GetUserSchedule200Response {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('streams' in value) || value['streams'] === undefined) return false;
    return true;
}

export function GetUserSchedule200ResponseFromJSON(json: any): GetUserSchedule200Response {
    return GetUserSchedule200ResponseFromJSONTyped(json, false);
}

export function GetUserSchedule200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserSchedule200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'streams': ((json['streams'] as Array<any>).map(GetYogsSchedule200ResponseStreamsInnerFromJSON)),
    };
}

export function GetUserSchedule200ResponseToJSON(value?: GetUserSchedule200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'streams': ((value['streams'] as Array<any>).map(GetYogsSchedule200ResponseStreamsInnerToJSON)),
    };
}

