/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetYogsSchedule200ResponseDaysInner } from './GetYogsSchedule200ResponseDaysInner';
import {
    GetYogsSchedule200ResponseDaysInnerFromJSON,
    GetYogsSchedule200ResponseDaysInnerFromJSONTyped,
    GetYogsSchedule200ResponseDaysInnerToJSON,
} from './GetYogsSchedule200ResponseDaysInner';
import type { Stream } from './Stream';
import {
    StreamFromJSON,
    StreamFromJSONTyped,
    StreamToJSON,
} from './Stream';

/**
 * 
 * @export
 * @interface GetYogsSchedule200Response
 */
export interface GetYogsSchedule200Response {
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200Response
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200Response
     */
    end: Date;
    /**
     * 
     * @type {number}
     * @memberof GetYogsSchedule200Response
     */
    initialDayIndex: number;
    /**
     * 
     * @type {Array<GetYogsSchedule200ResponseDaysInner>}
     * @memberof GetYogsSchedule200Response
     */
    days: Array<GetYogsSchedule200ResponseDaysInner>;
    /**
     * 
     * @type {Array<Stream>}
     * @memberof GetYogsSchedule200Response
     */
    streams: Array<Stream>;
}

/**
 * Check if a given object implements the GetYogsSchedule200Response interface.
 */
export function instanceOfGetYogsSchedule200Response(value: object): value is GetYogsSchedule200Response {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('initialDayIndex' in value) || value['initialDayIndex'] === undefined) return false;
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('streams' in value) || value['streams'] === undefined) return false;
    return true;
}

export function GetYogsSchedule200ResponseFromJSON(json: any): GetYogsSchedule200Response {
    return GetYogsSchedule200ResponseFromJSONTyped(json, false);
}

export function GetYogsSchedule200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetYogsSchedule200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'initialDayIndex': json['initialDayIndex'],
        'days': ((json['days'] as Array<any>).map(GetYogsSchedule200ResponseDaysInnerFromJSON)),
        'streams': ((json['streams'] as Array<any>).map(StreamFromJSON)),
    };
}

export function GetYogsSchedule200ResponseToJSON(value?: GetYogsSchedule200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'initialDayIndex': value['initialDayIndex'],
        'days': ((value['days'] as Array<any>).map(GetYogsSchedule200ResponseDaysInnerToJSON)),
        'streams': ((value['streams'] as Array<any>).map(StreamToJSON)),
    };
}

