/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner
 */
export interface GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner {
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner
     */
    id: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner
     */
    url: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner
     */
    color: string | null;
}

/**
 * Check if a given object implements the GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner interface.
 */
export function instanceOfGetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner(value: object): value is GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerFromJSON(json: any): GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner {
    return GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerFromJSONTyped(json, false);
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'color': json['color'],
    };
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerToJSON(value?: GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
        'imageUrl': value['imageUrl'],
        'color': value['color'],
    };
}

