/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner } from './GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner';
import {
    GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerFromJSON,
    GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerFromJSONTyped,
    GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerToJSON,
} from './GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner';
import type { GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner } from './GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner';
import {
    GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerFromJSON,
    GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerFromJSONTyped,
    GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerToJSON,
} from './GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner';

/**
 * 
 * @export
 * @interface GetYogsSchedule200ResponseDaysInnerStreamsInner
 */
export interface GetYogsSchedule200ResponseDaysInnerStreamsInner {
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    title: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    subtitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    markdownDescription?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    end: Date;
    /**
     * 
     * @type {Array<GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner>}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    creators?: Array<GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInner>;
    /**
     * 
     * @type {Array<GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner>}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    vods?: Array<GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner>;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInner
     */
    color: string | null;
}

/**
 * Check if a given object implements the GetYogsSchedule200ResponseDaysInnerStreamsInner interface.
 */
export function instanceOfGetYogsSchedule200ResponseDaysInnerStreamsInner(value: object): value is GetYogsSchedule200ResponseDaysInnerStreamsInner {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerFromJSON(json: any): GetYogsSchedule200ResponseDaysInnerStreamsInner {
    return GetYogsSchedule200ResponseDaysInnerStreamsInnerFromJSONTyped(json, false);
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetYogsSchedule200ResponseDaysInnerStreamsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'description': json['description'] == null ? undefined : json['description'],
        'markdownDescription': json['markdownDescription'] == null ? undefined : json['markdownDescription'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'creators': json['creators'] == null ? undefined : ((json['creators'] as Array<any>).map(GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerFromJSON)),
        'vods': json['vods'] == null ? undefined : ((json['vods'] as Array<any>).map(GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerFromJSON)),
        'color': json['color'],
    };
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerToJSON(value?: GetYogsSchedule200ResponseDaysInnerStreamsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'subtitle': value['subtitle'],
        'description': value['description'],
        'markdownDescription': value['markdownDescription'],
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'creators': value['creators'] == null ? undefined : ((value['creators'] as Array<any>).map(GetYogsSchedule200ResponseDaysInnerStreamsInnerCreatorsInnerToJSON)),
        'vods': value['vods'] == null ? undefined : ((value['vods'] as Array<any>).map(GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerToJSON)),
        'color': value['color'],
    };
}

