/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetYogsSchedule200ResponseStreamsInnerVodsInner
 */
export interface GetYogsSchedule200ResponseStreamsInnerVodsInner {
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseStreamsInnerVodsInner
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseStreamsInnerVodsInner
     */
    link: string;
}

/**
 * Check if a given object implements the GetYogsSchedule200ResponseStreamsInnerVodsInner interface.
 */
export function instanceOfGetYogsSchedule200ResponseStreamsInnerVodsInner(value: object): value is GetYogsSchedule200ResponseStreamsInnerVodsInner {
    if (!('link' in value) || value['link'] === undefined) return false;
    return true;
}

export function GetYogsSchedule200ResponseStreamsInnerVodsInnerFromJSON(json: any): GetYogsSchedule200ResponseStreamsInnerVodsInner {
    return GetYogsSchedule200ResponseStreamsInnerVodsInnerFromJSONTyped(json, false);
}

export function GetYogsSchedule200ResponseStreamsInnerVodsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetYogsSchedule200ResponseStreamsInnerVodsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'link': json['link'],
    };
}

export function GetYogsSchedule200ResponseStreamsInnerVodsInnerToJSON(value?: GetYogsSchedule200ResponseStreamsInnerVodsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'label': value['label'],
        'link': value['link'],
    };
}

