/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner
 */
export interface GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner {
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner
     */
    label?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner
     */
    link: string | null;
}

/**
 * Check if a given object implements the GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner interface.
 */
export function instanceOfGetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner(value: object): value is GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner {
    if (!('link' in value) || value['link'] === undefined) return false;
    return true;
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerFromJSON(json: any): GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner {
    return GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerFromJSONTyped(json, false);
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'link': json['link'],
    };
}

export function GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInnerToJSON(value?: GetYogsSchedule200ResponseDaysInnerStreamsInnerVodsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'label': value['label'],
        'link': value['link'],
    };
}

