/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stream } from './Stream';
import {
    StreamFromJSON,
    StreamFromJSONTyped,
    StreamToJSON,
} from './Stream';

/**
 * 
 * @export
 * @interface GetYogsSchedule200ResponseDaysInner
 */
export interface GetYogsSchedule200ResponseDaysInner {
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200ResponseDaysInner
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200ResponseDaysInner
     */
    end: Date;
    /**
     * 
     * @type {Array<Stream>}
     * @memberof GetYogsSchedule200ResponseDaysInner
     */
    streams: Array<Stream>;
}

/**
 * Check if a given object implements the GetYogsSchedule200ResponseDaysInner interface.
 */
export function instanceOfGetYogsSchedule200ResponseDaysInner(value: object): value is GetYogsSchedule200ResponseDaysInner {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('streams' in value) || value['streams'] === undefined) return false;
    return true;
}

export function GetYogsSchedule200ResponseDaysInnerFromJSON(json: any): GetYogsSchedule200ResponseDaysInner {
    return GetYogsSchedule200ResponseDaysInnerFromJSONTyped(json, false);
}

export function GetYogsSchedule200ResponseDaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetYogsSchedule200ResponseDaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'streams': ((json['streams'] as Array<any>).map(StreamFromJSON)),
    };
}

export function GetYogsSchedule200ResponseDaysInnerToJSON(value?: GetYogsSchedule200ResponseDaysInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'streams': ((value['streams'] as Array<any>).map(StreamToJSON)),
    };
}

