/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetYogsSchedule200ResponseStreamsInnerCreatorsInner } from './GetYogsSchedule200ResponseStreamsInnerCreatorsInner';
import {
    GetYogsSchedule200ResponseStreamsInnerCreatorsInnerFromJSON,
    GetYogsSchedule200ResponseStreamsInnerCreatorsInnerFromJSONTyped,
    GetYogsSchedule200ResponseStreamsInnerCreatorsInnerToJSON,
} from './GetYogsSchedule200ResponseStreamsInnerCreatorsInner';
import type { GetYogsSchedule200ResponseStreamsInnerVodsInner } from './GetYogsSchedule200ResponseStreamsInnerVodsInner';
import {
    GetYogsSchedule200ResponseStreamsInnerVodsInnerFromJSON,
    GetYogsSchedule200ResponseStreamsInnerVodsInnerFromJSONTyped,
    GetYogsSchedule200ResponseStreamsInnerVodsInnerToJSON,
} from './GetYogsSchedule200ResponseStreamsInnerVodsInner';

/**
 * 
 * @export
 * @interface GetYogsSchedule200ResponseStreamsInner
 */
export interface GetYogsSchedule200ResponseStreamsInner {
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    subtitle?: string;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    markdownDescription?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    end: Date;
    /**
     * 
     * @type {Array<GetYogsSchedule200ResponseStreamsInnerCreatorsInner>}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    creators?: Array<GetYogsSchedule200ResponseStreamsInnerCreatorsInner>;
    /**
     * 
     * @type {Array<GetYogsSchedule200ResponseStreamsInnerVodsInner>}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    vods?: Array<GetYogsSchedule200ResponseStreamsInnerVodsInner>;
    /**
     * 
     * @type {string}
     * @memberof GetYogsSchedule200ResponseStreamsInner
     */
    color: string;
}

/**
 * Check if a given object implements the GetYogsSchedule200ResponseStreamsInner interface.
 */
export function instanceOfGetYogsSchedule200ResponseStreamsInner(value: object): value is GetYogsSchedule200ResponseStreamsInner {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function GetYogsSchedule200ResponseStreamsInnerFromJSON(json: any): GetYogsSchedule200ResponseStreamsInner {
    return GetYogsSchedule200ResponseStreamsInnerFromJSONTyped(json, false);
}

export function GetYogsSchedule200ResponseStreamsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetYogsSchedule200ResponseStreamsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'description': json['description'] == null ? undefined : json['description'],
        'markdownDescription': json['markdownDescription'] == null ? undefined : json['markdownDescription'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'creators': json['creators'] == null ? undefined : ((json['creators'] as Array<any>).map(GetYogsSchedule200ResponseStreamsInnerCreatorsInnerFromJSON)),
        'vods': json['vods'] == null ? undefined : ((json['vods'] as Array<any>).map(GetYogsSchedule200ResponseStreamsInnerVodsInnerFromJSON)),
        'color': json['color'],
    };
}

export function GetYogsSchedule200ResponseStreamsInnerToJSON(value?: GetYogsSchedule200ResponseStreamsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'subtitle': value['subtitle'],
        'description': value['description'],
        'markdownDescription': value['markdownDescription'],
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'creators': value['creators'] == null ? undefined : ((value['creators'] as Array<any>).map(GetYogsSchedule200ResponseStreamsInnerCreatorsInnerToJSON)),
        'vods': value['vods'] == null ? undefined : ((value['vods'] as Array<any>).map(GetYogsSchedule200ResponseStreamsInnerVodsInnerToJSON)),
        'color': value['color'],
    };
}

