/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JJCampaignTwitch
 */
export interface JJCampaignTwitch {
    /**
     * 
     * @type {string}
     * @memberof JJCampaignTwitch
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JJCampaignTwitch
     */
    avatar: string;
    /**
     * 
     * @type {boolean}
     * @memberof JJCampaignTwitch
     */
    isLive: boolean;
    /**
     * 
     * @type {string}
     * @memberof JJCampaignTwitch
     */
    url: string;
}

/**
 * Check if a given object implements the JJCampaignTwitch interface.
 */
export function instanceOfJJCampaignTwitch(value: object): value is JJCampaignTwitch {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('isLive' in value) || value['isLive'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function JJCampaignTwitchFromJSON(json: any): JJCampaignTwitch {
    return JJCampaignTwitchFromJSONTyped(json, false);
}

export function JJCampaignTwitchFromJSONTyped(json: any, ignoreDiscriminator: boolean): JJCampaignTwitch {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'avatar': json['avatar'],
        'isLive': json['isLive'],
        'url': json['url'],
    };
}

export function JJCampaignTwitchToJSON(value?: JJCampaignTwitch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'avatar': value['avatar'],
        'isLive': value['isLive'],
        'url': value['url'],
    };
}

