/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JJCampaignTwitch } from './JJCampaignTwitch';
import {
    JJCampaignTwitchFromJSON,
    JJCampaignTwitchFromJSONTyped,
    JJCampaignTwitchToJSON,
} from './JJCampaignTwitch';
import type { CurrenciesSchema } from './CurrenciesSchema';
import {
    CurrenciesSchemaFromJSON,
    CurrenciesSchemaFromJSONTyped,
    CurrenciesSchemaToJSON,
} from './CurrenciesSchema';

/**
 * 
 * @export
 * @interface JJCampaign
 */
export interface JJCampaign {
    /**
     * 
     * @type {string}
     * @memberof JJCampaign
     */
    tiltifySlug: string;
    /**
     * 
     * @type {string}
     * @memberof JJCampaign
     */
    campaignName: string;
    /**
     * 
     * @type {string}
     * @memberof JJCampaign
     */
    tiltifyUrl: string;
    /**
     * 
     * @type {string}
     * @memberof JJCampaign
     */
    tiltifyName: string;
    /**
     * 
     * @type {string}
     * @memberof JJCampaign
     */
    tiltifyDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof JJCampaign
     */
    tiltifyCauseId?: string;
    /**
     * 
     * @type {string}
     * @memberof JJCampaign
     */
    avatar: string;
    /**
     * 
     * @type {CurrenciesSchema}
     * @memberof JJCampaign
     */
    raised: CurrenciesSchema;
    /**
     * 
     * @type {CurrenciesSchema}
     * @memberof JJCampaign
     */
    goal: CurrenciesSchema;
    /**
     * 
     * @type {JJCampaignTwitch}
     * @memberof JJCampaign
     */
    twitch?: JJCampaignTwitch;
}

/**
 * Check if a given object implements the JJCampaign interface.
 */
export function instanceOfJJCampaign(value: object): value is JJCampaign {
    if (!('tiltifySlug' in value) || value['tiltifySlug'] === undefined) return false;
    if (!('campaignName' in value) || value['campaignName'] === undefined) return false;
    if (!('tiltifyUrl' in value) || value['tiltifyUrl'] === undefined) return false;
    if (!('tiltifyName' in value) || value['tiltifyName'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('raised' in value) || value['raised'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    return true;
}

export function JJCampaignFromJSON(json: any): JJCampaign {
    return JJCampaignFromJSONTyped(json, false);
}

export function JJCampaignFromJSONTyped(json: any, ignoreDiscriminator: boolean): JJCampaign {
    if (json == null) {
        return json;
    }
    return {
        
        'tiltifySlug': json['tiltifySlug'],
        'campaignName': json['campaignName'],
        'tiltifyUrl': json['tiltifyUrl'],
        'tiltifyName': json['tiltifyName'],
        'tiltifyDescription': json['tiltifyDescription'] == null ? undefined : json['tiltifyDescription'],
        'tiltifyCauseId': json['tiltifyCauseId'] == null ? undefined : json['tiltifyCauseId'],
        'avatar': json['avatar'],
        'raised': CurrenciesSchemaFromJSON(json['raised']),
        'goal': CurrenciesSchemaFromJSON(json['goal']),
        'twitch': json['twitch'] == null ? undefined : JJCampaignTwitchFromJSON(json['twitch']),
    };
}

export function JJCampaignToJSON(value?: JJCampaign | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tiltifySlug': value['tiltifySlug'],
        'campaignName': value['campaignName'],
        'tiltifyUrl': value['tiltifyUrl'],
        'tiltifyName': value['tiltifyName'],
        'tiltifyDescription': value['tiltifyDescription'],
        'tiltifyCauseId': value['tiltifyCauseId'],
        'avatar': value['avatar'],
        'raised': CurrenciesSchemaToJSON(value['raised']),
        'goal': CurrenciesSchemaToJSON(value['goal']),
        'twitch': JJCampaignTwitchToJSON(value['twitch']),
    };
}

