/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JJCampaign } from './JJCampaign';
import {
    JJCampaignFromJSON,
    JJCampaignFromJSONTyped,
    JJCampaignToJSON,
} from './JJCampaign';

/**
 * 
 * @export
 * @interface JJCampaigns
 */
export interface JJCampaigns {
    /**
     * 
     * @type {number}
     * @memberof JJCampaigns
     */
    count: number;
    /**
     * 
     * @type {Array<JJCampaign>}
     * @memberof JJCampaigns
     */
    campaigns: Array<JJCampaign>;
    /**
     * 
     * @type {Date}
     * @memberof JJCampaigns
     */
    date: Date;
}

/**
 * Check if a given object implements the JJCampaigns interface.
 */
export function instanceOfJJCampaigns(value: object): value is JJCampaigns {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('campaigns' in value) || value['campaigns'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function JJCampaignsFromJSON(json: any): JJCampaigns {
    return JJCampaignsFromJSONTyped(json, false);
}

export function JJCampaignsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JJCampaigns {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'campaigns': ((json['campaigns'] as Array<any>).map(JJCampaignFromJSON)),
        'date': (new Date(json['date'])),
    };
}

export function JJCampaignsToJSON(value?: JJCampaigns | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'campaigns': ((value['campaigns'] as Array<any>).map(JJCampaignToJSON)),
        'date': ((value['date']).toISOString()),
    };
}

