/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrenciesSchema } from './CurrenciesSchema';
import {
    CurrenciesSchemaFromJSON,
    CurrenciesSchemaFromJSONTyped,
    CurrenciesSchemaToJSON,
} from './CurrenciesSchema';

/**
 * 
 * @export
 * @interface JJCause
 */
export interface JJCause {
    /**
     * 
     * @type {string}
     * @memberof JJCause
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof JJCause
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JJCause
     */
    logo: string;
    /**
     * 
     * @type {string}
     * @memberof JJCause
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof JJCause
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof JJCause
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof JJCause
     */
    donateUrl: string;
    /**
     * 
     * @type {CurrenciesSchema}
     * @memberof JJCause
     */
    raised: CurrenciesSchema;
}

/**
 * Check if a given object implements the JJCause interface.
 */
export function instanceOfJJCause(value: object): value is JJCause {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('logo' in value) || value['logo'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('donateUrl' in value) || value['donateUrl'] === undefined) return false;
    if (!('raised' in value) || value['raised'] === undefined) return false;
    return true;
}

export function JJCauseFromJSON(json: any): JJCause {
    return JJCauseFromJSONTyped(json, false);
}

export function JJCauseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JJCause {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'logo': json['logo'],
        'description': json['description'],
        'color': json['color'] == null ? undefined : json['color'],
        'url': json['url'],
        'donateUrl': json['donateUrl'],
        'raised': CurrenciesSchemaFromJSON(json['raised']),
    };
}

export function JJCauseToJSON(value?: JJCause | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'logo': value['logo'],
        'description': value['description'],
        'color': value['color'],
        'url': value['url'],
        'donateUrl': value['donateUrl'],
        'raised': CurrenciesSchemaToJSON(value['raised']),
    };
}

