/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JJLivestream
 */
export interface JJLivestream {
    /**
     * 
     * @type {string}
     * @memberof JJLivestream
     */
    channel: string | null;
    /**
     * 
     * @type {string}
     * @memberof JJLivestream
     */
    type: string;
}

/**
 * Check if a given object implements the JJLivestream interface.
 */
export function instanceOfJJLivestream(value: object): value is JJLivestream {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function JJLivestreamFromJSON(json: any): JJLivestream {
    return JJLivestreamFromJSONTyped(json, false);
}

export function JJLivestreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): JJLivestream {
    if (json == null) {
        return json;
    }
    return {
        
        'channel': json['channel'],
        'type': json['type'],
    };
}

export function JJLivestreamToJSON(value?: JJLivestream | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'channel': value['channel'],
        'type': value['type'],
    };
}

