/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrenciesSchema } from './CurrenciesSchema';
import {
    CurrenciesSchemaFromJSON,
    CurrenciesSchemaFromJSONTyped,
    CurrenciesSchemaToJSON,
} from './CurrenciesSchema';

/**
 * 
 * @export
 * @interface JJRaised
 */
export interface JJRaised {
    /**
     * 
     * @type {CurrenciesSchema}
     * @memberof JJRaised
     */
    yogscast?: CurrenciesSchema;
    /**
     * 
     * @type {CurrenciesSchema}
     * @memberof JJRaised
     */
    fundraisers?: CurrenciesSchema;
    /**
     * 
     * @type {CurrenciesSchema}
     * @memberof JJRaised
     */
    total: CurrenciesSchema;
}

/**
 * Check if a given object implements the JJRaised interface.
 */
export function instanceOfJJRaised(value: object): value is JJRaised {
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function JJRaisedFromJSON(json: any): JJRaised {
    return JJRaisedFromJSONTyped(json, false);
}

export function JJRaisedFromJSONTyped(json: any, ignoreDiscriminator: boolean): JJRaised {
    if (json == null) {
        return json;
    }
    return {
        
        'yogscast': json['yogscast'] == null ? undefined : CurrenciesSchemaFromJSON(json['yogscast']),
        'fundraisers': json['fundraisers'] == null ? undefined : CurrenciesSchemaFromJSON(json['fundraisers']),
        'total': CurrenciesSchemaFromJSON(json['total']),
    };
}

export function JJRaisedToJSON(value?: JJRaised | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'yogscast': CurrenciesSchemaToJSON(value['yogscast']),
        'fundraisers': CurrenciesSchemaToJSON(value['fundraisers']),
        'total': CurrenciesSchemaToJSON(value['total']),
    };
}

