/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JJUser
 */
export interface JJUser {
    /**
     * 
     * @type {number}
     * @memberof JJUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof JJUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof JJUser
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof JJUser
     */
    avatar: string;
    /**
     * 
     * @type {string}
     * @memberof JJUser
     */
    url: string;
}

/**
 * Check if a given object implements the JJUser interface.
 */
export function instanceOfJJUser(value: object): value is JJUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function JJUserFromJSON(json: any): JJUser {
    return JJUserFromJSONTyped(json, false);
}

export function JJUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): JJUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'avatar': json['avatar'],
        'url': json['url'],
    };
}

export function JJUserToJSON(value?: JJUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'avatar': value['avatar'],
        'url': value['url'],
    };
}

