/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverviewSchemaCollections
 */
export interface OverviewSchemaCollections {
    /**
     * 
     * @type {number}
     * @memberof OverviewSchemaCollections
     */
    redeemed: number;
    /**
     * 
     * @type {number}
     * @memberof OverviewSchemaCollections
     */
    total: number;
}

/**
 * Check if a given object implements the OverviewSchemaCollections interface.
 */
export function instanceOfOverviewSchemaCollections(value: object): value is OverviewSchemaCollections {
    if (!('redeemed' in value) || value['redeemed'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function OverviewSchemaCollectionsFromJSON(json: any): OverviewSchemaCollections {
    return OverviewSchemaCollectionsFromJSONTyped(json, false);
}

export function OverviewSchemaCollectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverviewSchemaCollections {
    if (json == null) {
        return json;
    }
    return {
        
        'redeemed': json['redeemed'],
        'total': json['total'],
    };
}

export function OverviewSchemaCollectionsToJSON(value?: OverviewSchemaCollections | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'redeemed': value['redeemed'],
        'total': value['total'],
    };
}

