/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDisplay
 */
export interface UserDisplay {
    /**
     * 
     * @type {number}
     * @memberof UserDisplay
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    primaryLiveStream: string;
    /**
     * 
     * @type {Date}
     * @memberof UserDisplay
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    profileImage: string;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    twitchLogin: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    tiltifySlug: string;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    tiltifyUrl: string;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    primaryColor: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDisplay
     */
    accentColor: string | null;
}

/**
 * Check if a given object implements the UserDisplay interface.
 */
export function instanceOfUserDisplay(value: object): value is UserDisplay {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('primaryLiveStream' in value) || value['primaryLiveStream'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('profileImage' in value) || value['profileImage'] === undefined) return false;
    if (!('twitchLogin' in value) || value['twitchLogin'] === undefined) return false;
    if (!('tiltifySlug' in value) || value['tiltifySlug'] === undefined) return false;
    if (!('tiltifyUrl' in value) || value['tiltifyUrl'] === undefined) return false;
    if (!('primaryColor' in value) || value['primaryColor'] === undefined) return false;
    if (!('accentColor' in value) || value['accentColor'] === undefined) return false;
    return true;
}

export function UserDisplayFromJSON(json: any): UserDisplay {
    return UserDisplayFromJSONTyped(json, false);
}

export function UserDisplayFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDisplay {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'primaryLiveStream': json['primaryLiveStream'],
        'createdAt': (new Date(json['createdAt'])),
        'username': json['username'],
        'profileImage': json['profileImage'],
        'twitchLogin': json['twitchLogin'],
        'tiltifySlug': json['tiltifySlug'],
        'tiltifyUrl': json['tiltifyUrl'],
        'primaryColor': json['primaryColor'],
        'accentColor': json['accentColor'],
    };
}

export function UserDisplayToJSON(value?: UserDisplay | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'primaryLiveStream': value['primaryLiveStream'],
        'createdAt': ((value['createdAt']).toISOString()),
        'username': value['username'],
        'profileImage': value['profileImage'],
        'twitchLogin': value['twitchLogin'],
        'tiltifySlug': value['tiltifySlug'],
        'tiltifyUrl': value['tiltifyUrl'],
        'primaryColor': value['primaryColor'],
        'accentColor': value['accentColor'],
    };
}

