/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserExtensionConfig
 */
export interface UserExtensionConfig {
    /**
     * 
     * @type {boolean}
     * @memberof UserExtensionConfig
     */
    hasCampaign: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserExtensionConfig
     */
    hasSchedule: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserExtensionConfig
     */
    tabs: Array<UserExtensionConfigTabsEnum>;
}


/**
 * @export
 */
export const UserExtensionConfigTabsEnum = {
    FullUser: 'full-user',
    UserSchedule: 'user-schedule',
    Yogs: 'yogs',
    Charities: 'charities',
    Fundraisers: 'fundraisers'
} as const;
export type UserExtensionConfigTabsEnum = typeof UserExtensionConfigTabsEnum[keyof typeof UserExtensionConfigTabsEnum];


/**
 * Check if a given object implements the UserExtensionConfig interface.
 */
export function instanceOfUserExtensionConfig(value: object): value is UserExtensionConfig {
    if (!('hasCampaign' in value) || value['hasCampaign'] === undefined) return false;
    if (!('hasSchedule' in value) || value['hasSchedule'] === undefined) return false;
    if (!('tabs' in value) || value['tabs'] === undefined) return false;
    return true;
}

export function UserExtensionConfigFromJSON(json: any): UserExtensionConfig {
    return UserExtensionConfigFromJSONTyped(json, false);
}

export function UserExtensionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserExtensionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'hasCampaign': json['hasCampaign'],
        'hasSchedule': json['hasSchedule'],
        'tabs': json['tabs'],
    };
}

export function UserExtensionConfigToJSON(value?: UserExtensionConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hasCampaign': value['hasCampaign'],
        'hasSchedule': value['hasSchedule'],
        'tabs': value['tabs'],
    };
}

