/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stream } from './Stream';
import {
    StreamFromJSON,
    StreamFromJSONTyped,
    StreamToJSON,
} from './Stream';

/**
 * 
 * @export
 * @interface UserScheduleSchema
 */
export interface UserScheduleSchema {
    /**
     * 
     * @type {string}
     * @memberof UserScheduleSchema
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof UserScheduleSchema
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserScheduleSchema
     */
    end: Date;
    /**
     * 
     * @type {Array<Stream>}
     * @memberof UserScheduleSchema
     */
    streams: Array<Stream>;
}

/**
 * Check if a given object implements the UserScheduleSchema interface.
 */
export function instanceOfUserScheduleSchema(value: object): value is UserScheduleSchema {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('streams' in value) || value['streams'] === undefined) return false;
    return true;
}

export function UserScheduleSchemaFromJSON(json: any): UserScheduleSchema {
    return UserScheduleSchemaFromJSONTyped(json, false);
}

export function UserScheduleSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserScheduleSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'streams': ((json['streams'] as Array<any>).map(StreamFromJSON)),
    };
}

export function UserScheduleSchemaToJSON(value?: UserScheduleSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'streams': ((value['streams'] as Array<any>).map(StreamToJSON)),
    };
}

