/* tslint:disable */
/* eslint-disable */
/**
 * Jingle Jam Community Page Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stream } from './Stream';
import {
    StreamFromJSON,
    StreamFromJSONTyped,
    StreamToJSON,
} from './Stream';

/**
 * 
 * @export
 * @interface YogsScheduleSchemaDaysInner
 */
export interface YogsScheduleSchemaDaysInner {
    /**
     * 
     * @type {Date}
     * @memberof YogsScheduleSchemaDaysInner
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof YogsScheduleSchemaDaysInner
     */
    end: Date;
    /**
     * 
     * @type {Array<Stream>}
     * @memberof YogsScheduleSchemaDaysInner
     */
    streams: Array<Stream>;
}

/**
 * Check if a given object implements the YogsScheduleSchemaDaysInner interface.
 */
export function instanceOfYogsScheduleSchemaDaysInner(value: object): value is YogsScheduleSchemaDaysInner {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('streams' in value) || value['streams'] === undefined) return false;
    return true;
}

export function YogsScheduleSchemaDaysInnerFromJSON(json: any): YogsScheduleSchemaDaysInner {
    return YogsScheduleSchemaDaysInnerFromJSONTyped(json, false);
}

export function YogsScheduleSchemaDaysInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): YogsScheduleSchemaDaysInner {
    if (json == null) {
        return json;
    }
    return {
        
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
        'streams': ((json['streams'] as Array<any>).map(StreamFromJSON)),
    };
}

export function YogsScheduleSchemaDaysInnerToJSON(value?: YogsScheduleSchemaDaysInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': ((value['start']).toISOString()),
        'end': ((value['end']).toISOString()),
        'streams': ((value['streams'] as Array<any>).map(StreamToJSON)),
    };
}

